/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StoreRouteRouteImport } from './routes/store/route'
import { Route as HqRouteRouteImport } from './routes/hq/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreDashboardRouteImport } from './routes/store/dashboard'
import { Route as HqStoresRouteImport } from './routes/hq/stores'
import { Route as HqDashboardRouteImport } from './routes/hq/dashboard'
import { Route as StoreSettingsStaffRouteImport } from './routes/store/settings/staff'
import { Route as StoreSettingsRolesRouteImport } from './routes/store/settings/roles'
import { Route as HqUsersStaffRouteImport } from './routes/hq/users/staff'
import { Route as HqUsersAdminsRouteImport } from './routes/hq/users/admins'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRouteRoute = StoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRouteRoute = HqRouteRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreDashboardRoute = StoreDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StoreRouteRoute,
} as any)
const HqStoresRoute = HqStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => HqRouteRoute,
} as any)
const HqDashboardRoute = HqDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HqRouteRoute,
} as any)
const StoreSettingsStaffRoute = StoreSettingsStaffRouteImport.update({
  id: '/settings/staff',
  path: '/settings/staff',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreSettingsRolesRoute = StoreSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => StoreRouteRoute,
} as any)
const HqUsersStaffRoute = HqUsersStaffRouteImport.update({
  id: '/users/staff',
  path: '/users/staff',
  getParentRoute: () => HqRouteRoute,
} as any)
const HqUsersAdminsRoute = HqUsersAdminsRouteImport.update({
  id: '/users/admins',
  path: '/users/admins',
  getParentRoute: () => HqRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hq': typeof HqRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/hq/dashboard': typeof HqDashboardRoute
  '/hq/stores': typeof HqStoresRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/hq/users/admins': typeof HqUsersAdminsRoute
  '/hq/users/staff': typeof HqUsersStaffRoute
  '/store/settings/roles': typeof StoreSettingsRolesRoute
  '/store/settings/staff': typeof StoreSettingsStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hq': typeof HqRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/hq/dashboard': typeof HqDashboardRoute
  '/hq/stores': typeof HqStoresRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/hq/users/admins': typeof HqUsersAdminsRoute
  '/hq/users/staff': typeof HqUsersStaffRoute
  '/store/settings/roles': typeof StoreSettingsRolesRoute
  '/store/settings/staff': typeof StoreSettingsStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hq': typeof HqRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/hq/dashboard': typeof HqDashboardRoute
  '/hq/stores': typeof HqStoresRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/hq/users/admins': typeof HqUsersAdminsRoute
  '/hq/users/staff': typeof HqUsersStaffRoute
  '/store/settings/roles': typeof StoreSettingsRolesRoute
  '/store/settings/staff': typeof StoreSettingsStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hq'
    | '/store'
    | '/login'
    | '/hq/dashboard'
    | '/hq/stores'
    | '/store/dashboard'
    | '/hq/users/admins'
    | '/hq/users/staff'
    | '/store/settings/roles'
    | '/store/settings/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hq'
    | '/store'
    | '/login'
    | '/hq/dashboard'
    | '/hq/stores'
    | '/store/dashboard'
    | '/hq/users/admins'
    | '/hq/users/staff'
    | '/store/settings/roles'
    | '/store/settings/staff'
  id:
    | '__root__'
    | '/'
    | '/hq'
    | '/store'
    | '/login'
    | '/hq/dashboard'
    | '/hq/stores'
    | '/store/dashboard'
    | '/hq/users/admins'
    | '/hq/users/staff'
    | '/store/settings/roles'
    | '/store/settings/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HqRouteRoute: typeof HqRouteRouteWithChildren
  StoreRouteRoute: typeof StoreRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/dashboard': {
      id: '/store/dashboard'
      path: '/dashboard'
      fullPath: '/store/dashboard'
      preLoaderRoute: typeof StoreDashboardRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/hq/stores': {
      id: '/hq/stores'
      path: '/stores'
      fullPath: '/hq/stores'
      preLoaderRoute: typeof HqStoresRouteImport
      parentRoute: typeof HqRouteRoute
    }
    '/hq/dashboard': {
      id: '/hq/dashboard'
      path: '/dashboard'
      fullPath: '/hq/dashboard'
      preLoaderRoute: typeof HqDashboardRouteImport
      parentRoute: typeof HqRouteRoute
    }
    '/store/settings/staff': {
      id: '/store/settings/staff'
      path: '/settings/staff'
      fullPath: '/store/settings/staff'
      preLoaderRoute: typeof StoreSettingsStaffRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/settings/roles': {
      id: '/store/settings/roles'
      path: '/settings/roles'
      fullPath: '/store/settings/roles'
      preLoaderRoute: typeof StoreSettingsRolesRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/hq/users/staff': {
      id: '/hq/users/staff'
      path: '/users/staff'
      fullPath: '/hq/users/staff'
      preLoaderRoute: typeof HqUsersStaffRouteImport
      parentRoute: typeof HqRouteRoute
    }
    '/hq/users/admins': {
      id: '/hq/users/admins'
      path: '/users/admins'
      fullPath: '/hq/users/admins'
      preLoaderRoute: typeof HqUsersAdminsRouteImport
      parentRoute: typeof HqRouteRoute
    }
  }
}

interface HqRouteRouteChildren {
  HqDashboardRoute: typeof HqDashboardRoute
  HqStoresRoute: typeof HqStoresRoute
  HqUsersAdminsRoute: typeof HqUsersAdminsRoute
  HqUsersStaffRoute: typeof HqUsersStaffRoute
}

const HqRouteRouteChildren: HqRouteRouteChildren = {
  HqDashboardRoute: HqDashboardRoute,
  HqStoresRoute: HqStoresRoute,
  HqUsersAdminsRoute: HqUsersAdminsRoute,
  HqUsersStaffRoute: HqUsersStaffRoute,
}

const HqRouteRouteWithChildren =
  HqRouteRoute._addFileChildren(HqRouteRouteChildren)

interface StoreRouteRouteChildren {
  StoreDashboardRoute: typeof StoreDashboardRoute
  StoreSettingsRolesRoute: typeof StoreSettingsRolesRoute
  StoreSettingsStaffRoute: typeof StoreSettingsStaffRoute
}

const StoreRouteRouteChildren: StoreRouteRouteChildren = {
  StoreDashboardRoute: StoreDashboardRoute,
  StoreSettingsRolesRoute: StoreSettingsRolesRoute,
  StoreSettingsStaffRoute: StoreSettingsStaffRoute,
}

const StoreRouteRouteWithChildren = StoreRouteRoute._addFileChildren(
  StoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HqRouteRoute: HqRouteRouteWithChildren,
  StoreRouteRoute: StoreRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
