/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StoreRouteRouteImport } from './routes/store/route'
import { Route as HqRouteRouteImport } from './routes/hq/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreDashboardRouteImport } from './routes/store/dashboard'
import { Route as HqUsersRouteImport } from './routes/hq/users'
import { Route as HqStoresRouteImport } from './routes/hq/stores'
import { Route as HqRolesRouteImport } from './routes/hq/roles'
import { Route as HqDashboardRouteImport } from './routes/hq/dashboard'
import { Route as StoreSettingsRolesRouteImport } from './routes/store/settings/roles'
import { Route as HqUsersUserIdRouteImport } from './routes/hq/users.$userId'
import { Route as HqStoresStoreIdRouteImport } from './routes/hq/stores.$storeId'
import { Route as HqRolesRoleIdRouteImport } from './routes/hq/roles.$roleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRouteRoute = StoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRouteRoute = HqRouteRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreDashboardRoute = StoreDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StoreRouteRoute,
} as any)
const HqUsersRoute = HqUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => HqRouteRoute,
} as any)
const HqStoresRoute = HqStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => HqRouteRoute,
} as any)
const HqRolesRoute = HqRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => HqRouteRoute,
} as any)
const HqDashboardRoute = HqDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HqRouteRoute,
} as any)
const StoreSettingsRolesRoute = StoreSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => StoreRouteRoute,
} as any)
const HqUsersUserIdRoute = HqUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => HqUsersRoute,
} as any)
const HqStoresStoreIdRoute = HqStoresStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => HqStoresRoute,
} as any)
const HqRolesRoleIdRoute = HqRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => HqRolesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hq': typeof HqRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/hq/dashboard': typeof HqDashboardRoute
  '/hq/roles': typeof HqRolesRouteWithChildren
  '/hq/stores': typeof HqStoresRouteWithChildren
  '/hq/users': typeof HqUsersRouteWithChildren
  '/store/dashboard': typeof StoreDashboardRoute
  '/hq/roles/$roleId': typeof HqRolesRoleIdRoute
  '/hq/stores/$storeId': typeof HqStoresStoreIdRoute
  '/hq/users/$userId': typeof HqUsersUserIdRoute
  '/store/settings/roles': typeof StoreSettingsRolesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hq': typeof HqRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/hq/dashboard': typeof HqDashboardRoute
  '/hq/roles': typeof HqRolesRouteWithChildren
  '/hq/stores': typeof HqStoresRouteWithChildren
  '/hq/users': typeof HqUsersRouteWithChildren
  '/store/dashboard': typeof StoreDashboardRoute
  '/hq/roles/$roleId': typeof HqRolesRoleIdRoute
  '/hq/stores/$storeId': typeof HqStoresStoreIdRoute
  '/hq/users/$userId': typeof HqUsersUserIdRoute
  '/store/settings/roles': typeof StoreSettingsRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hq': typeof HqRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/hq/dashboard': typeof HqDashboardRoute
  '/hq/roles': typeof HqRolesRouteWithChildren
  '/hq/stores': typeof HqStoresRouteWithChildren
  '/hq/users': typeof HqUsersRouteWithChildren
  '/store/dashboard': typeof StoreDashboardRoute
  '/hq/roles/$roleId': typeof HqRolesRoleIdRoute
  '/hq/stores/$storeId': typeof HqStoresStoreIdRoute
  '/hq/users/$userId': typeof HqUsersUserIdRoute
  '/store/settings/roles': typeof StoreSettingsRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hq'
    | '/store'
    | '/login'
    | '/hq/dashboard'
    | '/hq/roles'
    | '/hq/stores'
    | '/hq/users'
    | '/store/dashboard'
    | '/hq/roles/$roleId'
    | '/hq/stores/$storeId'
    | '/hq/users/$userId'
    | '/store/settings/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hq'
    | '/store'
    | '/login'
    | '/hq/dashboard'
    | '/hq/roles'
    | '/hq/stores'
    | '/hq/users'
    | '/store/dashboard'
    | '/hq/roles/$roleId'
    | '/hq/stores/$storeId'
    | '/hq/users/$userId'
    | '/store/settings/roles'
  id:
    | '__root__'
    | '/'
    | '/hq'
    | '/store'
    | '/login'
    | '/hq/dashboard'
    | '/hq/roles'
    | '/hq/stores'
    | '/hq/users'
    | '/store/dashboard'
    | '/hq/roles/$roleId'
    | '/hq/stores/$storeId'
    | '/hq/users/$userId'
    | '/store/settings/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HqRouteRoute: typeof HqRouteRouteWithChildren
  StoreRouteRoute: typeof StoreRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/dashboard': {
      id: '/store/dashboard'
      path: '/dashboard'
      fullPath: '/store/dashboard'
      preLoaderRoute: typeof StoreDashboardRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/hq/users': {
      id: '/hq/users'
      path: '/users'
      fullPath: '/hq/users'
      preLoaderRoute: typeof HqUsersRouteImport
      parentRoute: typeof HqRouteRoute
    }
    '/hq/stores': {
      id: '/hq/stores'
      path: '/stores'
      fullPath: '/hq/stores'
      preLoaderRoute: typeof HqStoresRouteImport
      parentRoute: typeof HqRouteRoute
    }
    '/hq/roles': {
      id: '/hq/roles'
      path: '/roles'
      fullPath: '/hq/roles'
      preLoaderRoute: typeof HqRolesRouteImport
      parentRoute: typeof HqRouteRoute
    }
    '/hq/dashboard': {
      id: '/hq/dashboard'
      path: '/dashboard'
      fullPath: '/hq/dashboard'
      preLoaderRoute: typeof HqDashboardRouteImport
      parentRoute: typeof HqRouteRoute
    }
    '/store/settings/roles': {
      id: '/store/settings/roles'
      path: '/settings/roles'
      fullPath: '/store/settings/roles'
      preLoaderRoute: typeof StoreSettingsRolesRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/hq/users/$userId': {
      id: '/hq/users/$userId'
      path: '/$userId'
      fullPath: '/hq/users/$userId'
      preLoaderRoute: typeof HqUsersUserIdRouteImport
      parentRoute: typeof HqUsersRoute
    }
    '/hq/stores/$storeId': {
      id: '/hq/stores/$storeId'
      path: '/$storeId'
      fullPath: '/hq/stores/$storeId'
      preLoaderRoute: typeof HqStoresStoreIdRouteImport
      parentRoute: typeof HqStoresRoute
    }
    '/hq/roles/$roleId': {
      id: '/hq/roles/$roleId'
      path: '/$roleId'
      fullPath: '/hq/roles/$roleId'
      preLoaderRoute: typeof HqRolesRoleIdRouteImport
      parentRoute: typeof HqRolesRoute
    }
  }
}

interface HqRolesRouteChildren {
  HqRolesRoleIdRoute: typeof HqRolesRoleIdRoute
}

const HqRolesRouteChildren: HqRolesRouteChildren = {
  HqRolesRoleIdRoute: HqRolesRoleIdRoute,
}

const HqRolesRouteWithChildren =
  HqRolesRoute._addFileChildren(HqRolesRouteChildren)

interface HqStoresRouteChildren {
  HqStoresStoreIdRoute: typeof HqStoresStoreIdRoute
}

const HqStoresRouteChildren: HqStoresRouteChildren = {
  HqStoresStoreIdRoute: HqStoresStoreIdRoute,
}

const HqStoresRouteWithChildren = HqStoresRoute._addFileChildren(
  HqStoresRouteChildren,
)

interface HqUsersRouteChildren {
  HqUsersUserIdRoute: typeof HqUsersUserIdRoute
}

const HqUsersRouteChildren: HqUsersRouteChildren = {
  HqUsersUserIdRoute: HqUsersUserIdRoute,
}

const HqUsersRouteWithChildren =
  HqUsersRoute._addFileChildren(HqUsersRouteChildren)

interface HqRouteRouteChildren {
  HqDashboardRoute: typeof HqDashboardRoute
  HqRolesRoute: typeof HqRolesRouteWithChildren
  HqStoresRoute: typeof HqStoresRouteWithChildren
  HqUsersRoute: typeof HqUsersRouteWithChildren
}

const HqRouteRouteChildren: HqRouteRouteChildren = {
  HqDashboardRoute: HqDashboardRoute,
  HqRolesRoute: HqRolesRouteWithChildren,
  HqStoresRoute: HqStoresRouteWithChildren,
  HqUsersRoute: HqUsersRouteWithChildren,
}

const HqRouteRouteWithChildren =
  HqRouteRoute._addFileChildren(HqRouteRouteChildren)

interface StoreRouteRouteChildren {
  StoreDashboardRoute: typeof StoreDashboardRoute
  StoreSettingsRolesRoute: typeof StoreSettingsRolesRoute
}

const StoreRouteRouteChildren: StoreRouteRouteChildren = {
  StoreDashboardRoute: StoreDashboardRoute,
  StoreSettingsRolesRoute: StoreSettingsRolesRoute,
}

const StoreRouteRouteWithChildren = StoreRouteRoute._addFileChildren(
  StoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HqRouteRoute: HqRouteRouteWithChildren,
  StoreRouteRoute: StoreRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
